### ISSUE TITLE
后端相关ignore以及数据库的问题

### ISSUE THREAD

**Issue by brickmaker** [brickmaker/SE-TSS#17]
Django相关的某些东西都应该ignore掉，比如log，__pycache__之类的东西，这些是自动生成的，不是自己写的，ignore掉。具体要ignore哪些，可以在这个 https://github.com/github/gitignore 里找到自己想要的配置。

数据库也应该ignore掉，自己对数据库的改动不能指望别人直接用这个数据库，而是要写个脚本，让别人可以从空的数据库得到你修改过得数据库。

@cherie11

**Comment by brickmaker** [comment]
django ignore参考这个：https://www.gitignore.io/api/django

**Comment by cherie11** [comment]
脚本和文件位置已移至相应文件夹下
